/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PokemonCard_pokemon.graphql
 * @generated SignedSource<<ca7cf77793117efa5aa3a75b427fd3bf>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PokemonCard_pokemon = {
  id: string;
  number: string;
  name: string;
  image: string;
  types: Array<string>;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "PokemonCard_pokemon",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "number",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "image",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "types",
      "storageKey": null
    }
  ],
  "type": "Pokemon"
};

module.exports = fragment;
