/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PokemonCard_pokemon.flow
 * @generated SignedSource<<4c1591dc2e8955d35544c5c324dbfd2e>>
 * @flow
 */

'use strict';

export type PokemonCard_pokemon = {
  id: string;
  number: string;
  name: string;
  image: string;
  types: Array<string>;
};
