/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PokemonQuery.graphql
 * @generated SignedSource<<a3218559e70126cc9dd9e215e7677c65>>
 * @relayHash 8216aebc46e2dd3361d1bd48c84e5bab
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query PokemonQuery(
  $id: ID!
) {
  pokemon(id: $id) {
    types
    attack
    hp
    speed
    specialDefense
    specialAttack
    image
    name
    defense
    weaknesses
    description
    weight(unit: KILOGRAM)
    height(unit: METER)
    number
    evolutions {
      id
      ...PokemonCard_pokemon
    }
    id
  }
}

fragment PokemonCard_pokemon on Pokemon {
  id
  number
  name
  image
  types
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "PokemonQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "id",
            "variableName": "id",
            "type": "ID!"
          }
        ],
        "concreteType": "Pokemon",
        "name": "pokemon",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "name",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "attack",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "hp",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "speed",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "specialDefense",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "specialAttack",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "image",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "defense",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "types",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "weaknesses",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "description",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "unit",
                "value": "KILOGRAM",
                "type": "WeightUnit"
              }
            ],
            "name": "weight",
            "storageKey": "weight{\"unit\":\"KILOGRAM\"}"
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "unit",
                "value": "METER",
                "type": "LengthUnit"
              }
            ],
            "name": "height",
            "storageKey": "height{\"unit\":\"METER\"}"
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "number",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Pokemon",
            "name": "evolutions",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "FragmentSpread",
                "name": "PokemonCard_pokemon",
                "args": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "PokemonQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "PokemonQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "id",
            "variableName": "id",
            "type": "ID!"
          }
        ],
        "concreteType": "Pokemon",
        "name": "pokemon",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "defense",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "types",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "hp",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "speed",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "specialDefense",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "specialAttack",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "image",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "name",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "attack",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "weaknesses",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "description",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "unit",
                "value": "KILOGRAM",
                "type": "WeightUnit"
              }
            ],
            "name": "weight",
            "storageKey": "weight{\"unit\":\"KILOGRAM\"}"
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "unit",
                "value": "METER",
                "type": "LengthUnit"
              }
            ],
            "name": "height",
            "storageKey": "height{\"unit\":\"METER\"}"
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "number",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Pokemon",
            "name": "evolutions",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "InlineFragment",
                "type": "Pokemon",
                "selections": [
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "number",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "name",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "image",
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": null,
                    "name": "types",
                    "storageKey": null
                  }
                ]
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query PokemonQuery(\n  $id: ID!\n) {\n  pokemon(id: $id) {\n    types\n    attack\n    hp\n    speed\n    specialDefense\n    specialAttack\n    image\n    name\n    defense\n    weaknesses\n    description\n    weight(unit: KILOGRAM)\n    height(unit: METER)\n    number\n    evolutions {\n      id\n      ...PokemonCard_pokemon\n    }\n    id\n  }\n}\n\nfragment PokemonCard_pokemon on Pokemon {\n  id\n  number\n  name\n  image\n  types\n}\n"
};

module.exports = batch;
