/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AppQuery.graphql
 * @generated SignedSource<<0cd0e9fce96643c8c0db30e8934d96d3>>
 * @relayHash b02ca6ee9bac1970f1271c3e4f0dc856
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query AppQuery {
  pokemons {
    ...index_pokemons
    id
  }
}

fragment index_pokemons on Pokemon {
  id
  ...PokemonCard_pokemon
}

fragment PokemonCard_pokemon on Pokemon {
  id
  number
  name
  image
  types
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "AppQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Pokemon",
        "name": "pokemons",
        "plural": true,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "index_pokemons",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "AppQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "AppQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Pokemon",
        "name": "pokemons",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "InlineFragment",
            "type": "Pokemon",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "number",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "name",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "image",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "types",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query AppQuery {\n  pokemons {\n    ...index_pokemons\n    id\n  }\n}\n\nfragment index_pokemons on Pokemon {\n  id\n  ...PokemonCard_pokemon\n}\n\nfragment PokemonCard_pokemon on Pokemon {\n  id\n  number\n  name\n  image\n  types\n}\n"
};

module.exports = batch;
