/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule index_pokemons.flow
 * @generated SignedSource<<38578b2adb8ac18425ef24dac400cdb3>>
 * @flow
 */

'use strict';

export type index_pokemons = {
  id: string;
};
